version: "3"
services:
  app:
    image: node:alpine
    volumes:
      - ${APP_PATH}:${DESTINATION_PATH}
    working_dir: ${DESTINATION_PATH}
    ports:
      - 3000:3000
    command: >
      sh -c "if [ ${NODE_ENV} != 'test' ] ; then
             npm run start
             else
             npm run test
             fi"